In [65]:
import numpy as np

In [66]:
# Q1
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a
temperature += 2

# b
temperature_fahrenheit = ((9/5) * temperature) + 32

# c
print(temperature[temperature > 32])

# d
print(np.size(temperature[temperature > 32]))

# e
# Vectorization and Boolean indexing eliminate the massive computational slowdowns caused by the Python interpreter. When you loop through a dataset in standard Python, the interpreter must evaluate every single row or element one by one.By replacing these loops with NumPy routines, the code shifts execution down to compiled, low-level C code, processing data in contiguous memory blocks at hardware speed.

[33 37 40 35 42]
5


In [67]:
# Q2
steps = np.array([
[5000, 6200, 7100],
[8000, 7500, 9000],
[4500, 5100, 4800],
[9000, 8500, 9500]])

# a
print(f"Total steps: {np.sum(steps)}")

# b
print(f"Mean steps: {steps.mean()}")

# c
print(f"Maximum steps: {steps.max()}")
print(f"Minimum steps: {steps.min()}")

# d
print(f"Total steps for each day: {np.sum(steps, axis = 0)}")

# e
print(f"Total steps for each user: {np.sum(steps, axis = 1)}")

# f
print(f"Position of maximum steps: {np.argmax(steps)}")

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Position of maximum steps: 11


In [68]:
# Q3
# a
original = np.array([1, 2, 3, 4, 5, 6])

# b
subset = original[1:5]
print(subset)

# c
subset[0] = 999
print(original)
print(subset)

# d
subset = original[1:5].copy()
subset[0] = 500
print(original)
print(subset)

# e
arr = np.arange(1, 13)
print(arr)
arr = np.reshape(arr, (3, 4))
print(arr)

# f
print(f"First row: {arr[0, :]}")
print(f"Last row: {arr[2, :]}")
print(f"Second column: {arr[:, 1]}")
print(f"Last column: {arr[:, 3]}")
print(arr[0:1, 1:3])

# g
arr_flattened = arr.flatten()
arr_raveled = arr.ravel()

# h
arr_raveled[0] = 67
print(arr)
print(arr_raveled)

# i
arr_flattened[1] = 500
print(arr)
print(arr_flattened)

# j
print(f"Shape: {original.shape}")
print(f"Dimensions: {original.ndim}")
print(f"Size: {np.size(original)}")
print(f"dtype: {original.dtype}")

[2 3 4 5]
[  1 999   3   4   5   6]
[999   3   4   5]
[  1 999   3   4   5   6]
[500   3   4   5]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Last column: [ 4  8 12]
[[2 3]]
[[67  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[67  2  3  4  5  6  7  8  9 10 11 12]
[[67  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[  1 500   3   4   5   6   7   8   9  10  11  12]
Shape: (6,)
Dimensions: 1
Size: 6
dtype: int64


In [69]:
# Q4
X = np.array([
[6, 70, 3],
[5, 50, 6],
[8, 80, 2],
[4, 30, 8]
])
y = np.array([40, 65, 30, 85])

# a
print("Shape:", X.shape)
print("Dimensions:", X.ndim)

# b
X_transpose = X.T
print(f"\nX.T: \n{X_transpose}")

# c
XTX = X.T @ X
print(f"\nX.T @ X: \n{XTX}")

# d
inverse_XTX = np.linalg.inv(XTX)
print(f"\nInverse of X.T @ X: \n{inverse_XTX}")

# e
beta = np.linalg.inv(X.T @ X) @ X.T @ y
print(f"\nCoefficients: {beta}")

# f
# beta[0] -> coefficient for Feature 1
# beta[1] -> coefficient for Feature 2
# beta[2] -> coefficient for Feature 3

# g
new_user = np.array([5, 40, 7])

predicted_assistance_score = new_user @ beta
print("\nPredicted assistance score:", predicted_assistance_score)

Shape: (4, 3)
Dimensions: 2

X.T: 
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X: 
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X: 
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

Coefficients: [-0.15921454  0.14083853 10.06302242]

Predicted assistance score: 75.27862544779117
