In [75]:
import numpy as np

In [ ]:
# Q1
array = np.array([1.0, 2.0, 3.0, 4.0, 5.0])

array += 2
array *= 3
array /= 2
array

array([ 4.5,  6. ,  7.5,  9. , 10.5])

In [77]:
# Q2
# a
arr = np.array([1, 2, 3, 4, 5])
arr = arr[::-1]
print(arr)

# b
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

vals, count = np.unique(x, return_counts=True)
# print(vals)
# print(count)

mode = vals[np.argmax(count)]
indices = np.flatnonzero(x == mode)
print(f"x's mode: {mode}")
print(f"x's corresponding indices: {indices}")

vals, count = np.unique(y, return_counts=True)
# print(vals)
# print(count)

mode = vals[np.argmax(count)] # found the first most frequent value, both 1 and 3 were possible
indices = np.flatnonzero(y == mode)
print(f"y's mode: {mode}")
print(f"y's corresponding indices: {indices}")

[5 4 3 2 1]
x's mode: 1
x's corresponding indices: [0 5 7 8 9]
y's mode: 1
y's corresponding indices: [0 1 2]


In [78]:
# Q3
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a
print(arr[0, 1])

# b
print(arr[2, 0])

20
70


In [79]:
# Q4
daksh = np.linspace(10, 100, 25)
print("\nDimensions:", np.ndim(daksh))
print("Shape:", np.shape(daksh))
print("Total elements:", np.size(daksh))
print("Data type of each element:", daksh.dtype)
print("Total bytes consumed:", daksh.nbytes)

transpose_reshape = daksh.reshape(1, -1)
print(f"\nTranspose using reshape(): \n{transpose_reshape}\n")

transpose_T = daksh.T
print(f"Using T attribute: \n{transpose_T}")


Dimensions: 1
Shape: (25,)
Total elements: 25
Data type of each element: float64
Total bytes consumed: 200

Transpose using reshape(): 
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]

Using T attribute: 
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [80]:
# Q5
ucs420_daksh = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35])
ucs420_daksh = np.reshape(ucs420_daksh, (3, 4))
print(ucs420_daksh)

print(f"\nMean: {ucs420_daksh.mean()}")
print(f"Median: {np.median(ucs420_daksh)}")
print(f"Max: {ucs420_daksh.max()}")
print(f"Min: {ucs420_daksh.min()}")
print(f"Unique elements: {np.unique(ucs420_daksh)}\n")

reshaped_ucs420_daksh = np.reshape(ucs420_daksh, (4, 3))
print(f"Reshaped array: \n{reshaped_ucs420_daksh}\n")

resized_ucs420_daksh = np.resize(ucs420_daksh, (2, 3))
print(f"Resized array: \n{resized_ucs420_daksh}")

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array: 
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array: 
[[10 20 30]
 [40 50 60]]
